server:
  port: ":8080"
  server_mode: "development"
  jwt_secret: "your-secret-key-change-this-in-production"

database:
  db_host: "localhost"
  db_port: "5432"
  db_user: "postgres"
  db_password: "password"
  db_name: "hospital_db"
  db_ssl_mode: "disable"
  db_timezone: "Asia/Bangkok"
